first2/urls.py
from django.urls import path
from first2.views import* 
app_name='first2'
urlpatterns =[
    path('generic/',generic,name='generic')
]

specific_genericproject/urls.py
from django.contrib import admin
from django.urls import path,include
import first2
from first1.views import*
urlpatterns = [
    path('admin/', admin.site.urls),
    path('first/',first,name='first'),
    path('second/',second,name='second'),
    path('first2/',include("first2.urls")),

]

first1/models.py
from django.db import models

# Create your models here.

first2/models.py
from django.db import models

# Create your models here.

first1/views.py
from django.shortcuts import render

# Create your views here.
def first(request):
    return render(request,'firstg.html')

def second(request):
    return render(request,'secondG.html')

first2/views.py
from django.shortcuts import render

# Create your views here.
def generic(request):
    return render(request,'firstS.html')

templates/firstS.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
    <h1>this is spesific urls</h1>
    <button><a href="{% url 'first' %}">go to generic first</a></button>
    <button><a href="{% url 'second' %}">go to generic second</a></button>
    </center>
</body>
</html>

templates/firstg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
    <h1>this is generic firstG</h1>
    <button><a href="{% url 'first2:generic' %}">go to specific</a></button>
    </center>
</body>
</html>

templates/secondG.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
    <h1>this is generic secondG</h1>
    <button><a href="{% url 'first2:generic'%}">go to specific</a></button>
    </center>
</body>
</html>